# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener:  force
  body_converter:
    enabled: true
  view:
    view_response_listener: true
    formats: { json: true, xml: false, rss: false }

  serializer:
    serialize_null: true
#    allowed_methods_listener:  true
  routing_loader:
      include_format: false
      default_format: json
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
      - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
